name: nissenger_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.8+10

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  font_awesome_flutter: ^10.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_slider_indicator: ^1.0.0
  flutter_screenutil: ^5.5.4
  intl: ^0.17.0
  flutter_native_splash: ^2.2.14
  flutter_launcher_icons: ^0.11.0
  flutter_dotenv: ^5.0.2
  dio: ^4.0.6
  connectivity_plus: ^3.0.2
  url_launcher: ^6.1.7
  appmetrica_plugin: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#2A81DD"
  image: assets/images/splash-logo.png
  fullscreen: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/images/onboarding/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/Sf-Pro-Display/Sf-Pro-Display-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sf-Pro-Display/Sf-Pro-Display-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sf-Pro-Display/Sf-Pro-Display-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sf-Pro-Display/Sf-Pro-Display-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
